# Generated by Django 5.2.6 on 2025-09-08 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_description_taskimage_taskmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("finish_to_start", "Finish to Start"),
                            ("start_to_start", "Start to Start"),
                            ("finish_to_finish", "Finish to Finish"),
                            ("start_to_finish", "Start to Finish"),
                        ],
                        default="finish_to_start",
                        max_length=20,
                        verbose_name="dependency type",
                    ),
                ),
                (
                    "lag_days",
                    models.IntegerField(
                        default=0,
                        help_text="Number of days to add to the dependency",
                        verbose_name="lag days",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "task dependency",
                "verbose_name_plural": "task dependencies",
                "ordering": ["predecessor__title", "successor__title"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["start_date"], name="tasks_task_start_d_eb2c37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["end_date"], name="tasks_task_end_dat_116fa9_idx"
            ),
        ),
        migrations.AddField(
            model_name="taskdependency",
            name="predecessor",
            field=models.ForeignKey(
                help_text="Task that must be completed before the successor",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="successor_dependencies",
                to="tasks.task",
                verbose_name="predecessor",
            ),
        ),
        migrations.AddField(
            model_name="taskdependency",
            name="successor",
            field=models.ForeignKey(
                help_text="Task that depends on the predecessor",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predecessor_dependencies",
                to="tasks.task",
                verbose_name="successor",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskdependency",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("predecessor", models.F("successor")), _negated=True
                ),
                name="task_dependency_no_self_reference",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskdependency",
            unique_together={("predecessor", "successor")},
        ),
    ]
